# Generated by Django 5.0.6 on 2024-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_films_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="films",
            name="pic",
            field=models.FileField(upload_to="pics"),
        ),
    ]
